[project]
name = "simple-ocr"
version = "0.1.0"
description = "A simple OCR app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit",
    "pillow",
    "pytesseract"
]

[tool.poetry]
package-mode = false
